language: php

sudo: false

php:
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction

script:
    - ./resources/build/tools/phpunit.phar --configuration ./resources/build/travis-ci.xml

notifications:
  email: false

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml


